export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const FILTER_CATE_SUCCESS = 'FILTER_CATE_SUCCESS';
export const FILTER_CATE = 'FILTER_CATE';
 
export const ADD_CATE = 'ADD_CATE';
export const ADD_CATE_SUCCESS = 'ADD_CATE_SUCCESS';
export const ADD_CATE_ERROR = 'ADD_CATE_ERROR';
export const UPDATE_CATE = 'UPDATE_CATE';
export const DELETE_CATE = 'DELETE_CATE';